export const types = {
    // 登录请求状态
    FETCH_LOGIN_REQUEST: 'LOGIN/FETCH_LOGIN_REQUEST',
    FETCH_LOGIN_SUCCESS: 'LOGIN/FETCH_LOGIN_SUCCESS',
    FETCH_LOGIN_FAILURE: 'LOGIN/FETCH_LOGIN_FAILURE'
};
