export const types = {
    // 首页轮播图
    FETCH_SLIDE_REQUEST: 'HOME/FETCH_SLIDE_REQUEST',
    FETCH_SLIDE_SUCCESS: 'HOME/FETCH_SLIDE_SUCCESS',
    FETCH_SLIDE_FAIL: 'HOME/FETCH_SLIDE_FAIL',
    // 首页常用设备
    FETCH_DEVICE_REQUEST: 'HOME/FETCH_DEVICE_REQUEST',
    FETCH_DEVICE_SUCCESS: 'HOME/FETCH_DEVICE_SUCCESS',
    FETCH_DEVICE_FAIL: 'HOME/FETCH_DEVICE_FAIL',
};
